/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Alimento;
import Controller.Instituicao;
import Controller.Saida;
import Model.Auxiliar;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author w1n3
 */
public class CadastroSaida extends javax.swing.JFrame {

    
    private int id_instituicao = -1, id_alimento = -1;
    /**
     * Creates new form CadastroEntrega
     */
    public CadastroSaida() {
        initComponents();
    }
    
    private void reset(){
        txtAlimento.setText("");
        txtInstituicao.setText("");
        txtQtdItens.setText("");
        txtQtdItens.setEnabled(false);
        datePicker.setDate(null);
        
        btnPesquisaInstituicao.setEnabled(true);
        txtInstituicao.setEnabled(true);
        btnPesquisaAlimento.setEnabled(true);
        txtAlimento.setEnabled(true);
        id_instituicao = -1;
        id_alimento = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPesquisaInstituicao = new javax.swing.JButton();
        txtInstituicao = new javax.swing.JTextField();
        lblPesquisaInstituicao = new javax.swing.JLabel();
        lblInstituicao = new javax.swing.JLabel();
        txtAlimento = new javax.swing.JTextField();
        btnPesquisaAlimento = new javax.swing.JButton();
        lblPesquisaAlimento = new javax.swing.JLabel();
        lblAlimento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        lblQtdItens = new javax.swing.JLabel();
        txtQtdItens = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mItemPrincipal = new javax.swing.JMenuItem();
        mItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPesquisaInstituicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pesquisa.png"))); // NOI18N
        btnPesquisaInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaInstituicaoActionPerformed(evt);
            }
        });

        lblPesquisaInstituicao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPesquisaInstituicao.setEnabled(false);

        lblInstituicao.setText("Instituição");

        btnPesquisaAlimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pesquisa.png"))); // NOI18N
        btnPesquisaAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaAlimentoActionPerformed(evt);
            }
        });

        lblPesquisaAlimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPesquisaAlimento.setEnabled(false);

        lblAlimento.setText("Alimento");

        jLabel1.setText("Data");

        lblQtdItens.setText("UND DE MEDIDA");

        txtQtdItens.setEnabled(false);
        txtQtdItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdItensActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jMenu1.setText("Arquivo");

        mItemPrincipal.setText("Menu Principal");
        mItemPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemPrincipalActionPerformed(evt);
            }
        });
        jMenu1.add(mItemPrincipal);

        mItemSair.setText("Sair");
        mItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(mItemSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAlimento)
                                    .addComponent(lblInstituicao)
                                    .addComponent(txtInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                    .addComponent(txtAlimento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPesquisaAlimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPesquisaAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPesquisaInstituicao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPesquisaInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQtdItens)
                            .addComponent(txtQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInstituicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisaInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisaInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAlimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisaAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisaAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQtdItens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemPrincipalActionPerformed
        this.setVisible(false);
        Auxiliar.trocarTela(new PrincipalAdm());
    }//GEN-LAST:event_mItemPrincipalActionPerformed

    private void mItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSairActionPerformed
        if (Model.Auxiliar.confirmarSaida()) System.exit(0);
    }//GEN-LAST:event_mItemSairActionPerformed

    private void btnPesquisaInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaInstituicaoActionPerformed
        String txt = txtInstituicao.getText();
        if (txt.equals("")){
            Auxiliar.errMsg(this, "Campo \'Instituicao\' vazio.", true);
            return;
        }

        // SE FOR NÚMERO, PROCURA POR ID, SENÃO PESQUISA POR NOME
        Instituicao i = new Instituicao();
        boolean sucesso = Auxiliar.isNumeric(txt) ? i.instituicaoPorId(Integer.parseInt(txt)) : i.instituicaoPorNome(txt);
        if (sucesso){
            id_instituicao = i.getId();

            java.net.URL imgURL = getClass().getResource("/images/success.png");
            ImageIcon icon = Auxiliar.createImageIcon(imgURL, "Instituicão encontrada");
            lblPesquisaInstituicao.setIcon(icon);
            txtInstituicao.setEnabled(false);
            btnPesquisaInstituicao.setEnabled(false);
            txtInstituicao.setText(i.getNome());
        } else {
            Auxiliar.errMsg(this, "Nenhuma instituição encontrada", true);
            java.net.URL imgURL = getClass().getResource("/images/failure.png");
            ImageIcon icon = Auxiliar.createImageIcon(imgURL, "Instituição não Encontrada");
            lblPesquisaInstituicao.setIcon(icon);
        }
    }//GEN-LAST:event_btnPesquisaInstituicaoActionPerformed

    private void btnPesquisaAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaAlimentoActionPerformed
        String txt = txtAlimento.getText();
        if (txtAlimento.getText().equals("")){
            Auxiliar.errMsg(this, "Campo \'Alimento\' vazio.", true);
            return;
        }

        Alimento a = new Alimento();

        boolean sucesso = Auxiliar.isNumeric(txt) ?
        a.consultar_por_id(Integer.parseInt(txt)) : a.consultar_por_nome(txt);
        if (sucesso){
            java.net.URL imgURL = getClass().getResource("/images/success.png");
            ImageIcon icon = Auxiliar.createImageIcon(imgURL, "Alimento encontrada");
            lblPesquisaAlimento.setIcon(icon);
            btnPesquisaAlimento.setEnabled(false);
            txtAlimento.setEnabled(false);
            txtQtdItens.setEnabled(true);

            txtAlimento.setText(a.getNome());
            lblQtdItens.setText(a.getMedida());
            id_alimento = a.getId_alimento();
        } else {
            Auxiliar.errMsg(this, "Nenhum alimento encontrado", true);
            java.net.URL imgURL = getClass().getResource("/images/failure.png");
            ImageIcon icon = Auxiliar.createImageIcon(imgURL, "Alimento Não Encontrado");
            lblPesquisaAlimento.setIcon(icon);
        }
    }//GEN-LAST:event_btnPesquisaAlimentoActionPerformed

    private void txtQtdItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdItensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdItensActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        reset();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String erro = "";
        if (txtQtdItens.getText().equals("") || !Auxiliar.isNumeric(txtQtdItens.getText()))
            erro += "Quantidade de itens inválida";
        
        if (id_instituicao == -1) erro += "Nenhuma instituição carregada";
        
        if (id_alimento == -1) erro += "Nenhum alimento selecionado";        
        
        Date d = datePicker.getDate();
        if (d == null) erro += "Data inválida\n";
        
        Saida s = new Saida();
        s.setId_alimento(id_alimento);
        s.setQtd_alimento(Integer.parseInt(txtQtdItens.getText()));
        s.setId_instituicao(id_instituicao);
        Format formatter = new SimpleDateFormat("dd/MM/yyyy");
        s.setData(formatter.format(d));
        
        if (!(erro += s.validar()).equals("")){
            Auxiliar.errMsg(this, erro, true);
        } else if (s.cadastrar()){
            Auxiliar.msg(this, "Saída cadastrada com sucesso", true);
            reset();
        } else {
            Auxiliar.errMsg(this, "Erro no BD", true);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroSaida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisaAlimento;
    private javax.swing.JButton btnPesquisaInstituicao;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAlimento;
    private javax.swing.JLabel lblInstituicao;
    private javax.swing.JLabel lblPesquisaAlimento;
    private javax.swing.JLabel lblPesquisaInstituicao;
    private javax.swing.JLabel lblQtdItens;
    private javax.swing.JMenuItem mItemPrincipal;
    private javax.swing.JMenuItem mItemSair;
    private javax.swing.JTextField txtAlimento;
    private javax.swing.JTextField txtInstituicao;
    private javax.swing.JTextField txtQtdItens;
    // End of variables declaration//GEN-END:variables
}
