/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Consultas;
import Model.Auxiliar;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre
 */
public class InterfaceConsultas extends javax.swing.JFrame {   
    
    boolean showTela = true;
    
    public InterfaceConsultas() {
        initComponents();
        reset();
    }
    
    private void reset(){
        lbl1.setVisible(false);
        txt1.setVisible(false);
        txt1.setText("");
        lbl2.setVisible(false);
        txt2.setVisible(false);
        txt2.setText("");
        lbl3.setVisible(false);
        txt3.setVisible(false);
        txt3.setText("");
        lbl4.setVisible(false);
        txt4.setVisible(false);  
        txt4.setText("");
        btnConsultar.setEnabled(false);
        // boa gambiarra essa
        DefaultTableModel dtm;
        String [][] dados = new String[1][1];
        dados[0][0] = "";        
        String [] columnNames = {""};
        dtm = new DefaultTableModel(dados, columnNames);
        tbl.setModel(dtm);
    }
    
    private void ativarConsulta0(){
        lbl1.setText("Instituicao");
        lbl1.setVisible(true);
        txt1.setVisible(true);
    }
    
    private void ativarConsulta1(){
        lbl1.setText("Instituicao");
        lbl1.setVisible(true);
        txt1.setVisible(true);
        lbl2.setText("Data");
        lbl2.setVisible(true);
        txt2.setVisible(true);      
    }
    
    private boolean validarConsulta0(){
        String erro = "";
        String inst = txt1.getText();
        if (inst.isEmpty() || inst.length() >= 150){
            erro += "Instituição inválida\n";
        } 
        if (!erro.equals("")){             
            Auxiliar.errMsg(this, erro, showTela);
            return false;
        } 
        return true;
    }
    
    private boolean validarConsulta1(){
        String erro = "";
        String inst = txt1.getText();
        if (inst.isEmpty() || inst.length() >= 150){
            erro += "Instituição inválida\n";
        }        
        
        if (txt2.getText().length() != 10){
            erro += "Data inválida\n";
        }
        
        if (!erro.equals("")){             
            Auxiliar.errMsg(this, erro, showTela);
            return false;
        } 
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbConsulta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        lbl2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        lbl4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        mItemPrincipal = new javax.swing.JMenuItem();
        mItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Consultas");

        cmbConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listar Contas por Instituição", "Entradas e Saídas realizadas em um dia" }));
        cmbConsulta.setSelectedIndex(-1);
        cmbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConsultaActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione a Consulta");

        btnLimpar.setLabel("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lbl1.setText("Instituicao");

        lbl2.setText("Instituicao");

        lbl3.setText("Instituicao");

        lbl4.setText("Instituicao");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        menuArquivo.setText("Arquivo");

        mItemPrincipal.setText("Menu Principal");
        mItemPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemPrincipalActionPerformed(evt);
            }
        });
        menuArquivo.add(mItemPrincipal);

        mItemSair.setText("Sair");
        mItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(mItemSair);

        jMenuBar1.add(menuArquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(cmbConsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl1)
                            .addComponent(lbl3)
                            .addComponent(txt3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txt1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl4)
                                .addComponent(txt4))
                            .addComponent(lbl2)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemPrincipalActionPerformed
        this.setVisible(false);
        Auxiliar.trocarTela(new PrincipalAdm());
    }//GEN-LAST:event_mItemPrincipalActionPerformed

    private void mItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSairActionPerformed
        if (Model.Auxiliar.confirmarSaida()) System.exit(0);
    }//GEN-LAST:event_mItemSairActionPerformed

    private void cmbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConsultaActionPerformed
        reset();
        switch (cmbConsulta.getSelectedIndex()){
            case 0: ativarConsulta0(); btnConsultar.setEnabled(true); break;
            case 1: ativarConsulta1(); btnConsultar.setEnabled(true); break;
            //case 2: ativarConsulta2(); break;                
        }

    }//GEN-LAST:event_cmbConsultaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        reset();
        cmbConsulta.setSelectedIndex(-1);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Consultas c = new Consultas();
        switch(cmbConsulta.getSelectedIndex()){
            case 0: 
                if (validarConsulta0()){
                    List<Map<String,Object>> lst = c.ContasPorInstituicao(txt1.getText());
                    if (lst == null){
                        Auxiliar.errMsg(this, "Nenhuma conta encontrada", showTela);
                        reset();
                    } else {
                        String[][] dados = new String[lst.size()][4];
                        for (int i = 0; i < lst.size(); i++){
                            String [] linha = {
                                String.valueOf(lst.get(i).get("nome")), 
                                String.valueOf(lst.get(i).get("descricao")), 
                                String.valueOf(lst.get(i).get("matricula")), 
                                String.valueOf(lst.get(i).get("usuario"))
                            };
                            dados[i] = linha;
                        }
                        
                        String [] columnNames = {"Nome", "Permissão", "Matrícula", "Usuário"};
                        
                        DefaultTableModel tm = new DefaultTableModel(dados, columnNames);
                        tbl.setModel(tm);
                    }
                }
                break;
            case 1:
                if (validarConsulta1()){
                    List<Map<String,Object>> lstEntrada = c.EntradaPorData(txt1.getText(), txt2.getText());
                    List<Map<String,Object>> lstSaida = c.SaidaPorData(txt1.getText(), txt2.getText());
                    if (lstEntrada == null && lstSaida == null){
                        Auxiliar.errMsg(this, "Nenhuma entrada ou saída encontrada", showTela);
                        reset();
                    } else {
                        String[][] dados = new String[lstEntrada.size() + lstSaida.size()][2];
                        System.out.println(lstEntrada);
                        for (int i = 0; i < lstEntrada.size(); i++){
                            String [] linha = {
                                String.valueOf(lstEntrada.get(i).get("alimento")), 
                                "+" + String.valueOf(lstEntrada.get(i).get("qtd_alimento"))
                            };
                            dados[i] = linha;
                        }
                        System.out.println(lstSaida);
                        for (int i = 0; i < lstSaida.size(); i++){
                            String [] linha = {
                                String.valueOf(lstSaida.get(i).get("alimento")), 
                                "-" + String.valueOf(lstSaida.get(i).get("qtd_alimento"))
                            };
                            dados[i+lstEntrada.size()] = linha;
                        }
                        
                        String [] columnNames = {"Alimento", "Quantidade"};
                        
                        DefaultTableModel tm = new DefaultTableModel(dados, columnNames) {
                            @Override
                            public boolean isCellEditable(int row, int column) {
                                return false;
                            }
                        };
                        tbl.setModel(tm);
                    }
                }
                break;
                
            default:
                Auxiliar.errMsg(this, "Nenhuma consulta selecionada", showTela);
                break; 
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmbConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JMenuItem mItemPrincipal;
    private javax.swing.JMenuItem mItemSair;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    // End of variables declaration//GEN-END:variables
}
