/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Auxiliar;
import Model.Sessao;
import java.awt.BorderLayout;
import View.CadastroPessoa;

/**
 *
 * @author Andre
 */
public class PrincipalAdm extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalAdm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mItemTeste = new javax.swing.JMenuItem();
        mItemLogout = new javax.swing.JMenuItem();
        mItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mItemPessoa = new javax.swing.JMenuItem();
        mItemInstituicao = new javax.swing.JMenuItem();
        mItemAlimento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivo");

        mItemTeste.setText("Teste");
        mItemTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemTesteActionPerformed(evt);
            }
        });
        jMenu1.add(mItemTeste);

        mItemLogout.setText("Logout");
        mItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mItemLogout);

        mItemSair.setText("Sair");
        mItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(mItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastrar");

        mItemPessoa.setText("Pessoa");
        mItemPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(mItemPessoa);

        mItemInstituicao.setText("Instituição");
        mItemInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemInstituicaoActionPerformed(evt);
            }
        });
        jMenu2.add(mItemInstituicao);

        mItemAlimento.setText("Alimento");
        mItemAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemAlimentoActionPerformed(evt);
            }
        });
        jMenu2.add(mItemAlimento);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSairActionPerformed
        if (Model.Auxiliar.confirmarSaida()) System.exit(0);
    }//GEN-LAST:event_mItemSairActionPerformed

    private void mItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemLogoutActionPerformed
        Sessao.destroy();
        this.setVisible(false);        
        Auxiliar.trocarTela(new Login());       
    }//GEN-LAST:event_mItemLogoutActionPerformed

    private void mItemPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemPessoaActionPerformed
        this.setVisible(false);        
        Auxiliar.trocarTela(new CadastroPessoa());    
    }//GEN-LAST:event_mItemPessoaActionPerformed

    private void mItemInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemInstituicaoActionPerformed
        this.setVisible(false);        
        Auxiliar.trocarTela(new CadastroInstituicao());    
    }//GEN-LAST:event_mItemInstituicaoActionPerformed

    private void mItemAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemAlimentoActionPerformed
        this.setVisible(false);        
        Auxiliar.trocarTela(new CadastroAlimento());    
    }//GEN-LAST:event_mItemAlimentoActionPerformed

    private void mItemTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemTesteActionPerformed
        CadastroPessoa c = new CadastroPessoa();
        this.add(c,BorderLayout.CENTER); 
    }//GEN-LAST:event_mItemTesteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItemAlimento;
    private javax.swing.JMenuItem mItemInstituicao;
    private javax.swing.JMenuItem mItemLogout;
    private javax.swing.JMenuItem mItemPessoa;
    private javax.swing.JMenuItem mItemSair;
    private javax.swing.JMenuItem mItemTeste;
    // End of variables declaration//GEN-END:variables
}
