package merendaprojectdb;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaCapaRelatorio extends javax.swing.JFrame {
    TelaCardapio cardapio;
    private CapaDados capa;
    private DefaultTableModel tabelaMatricula;
    private DefaultTableModel tabelaDesjejum;
    private DefaultTableModel tabelaMaisEducacao1;
    private DefaultTableModel tabelaMaisEducacao2;
    private DefaultTableModel tabelaTotal;
    public TelaCapaRelatorio() {
        initComponents();
        this.tabelaMatricula = (DefaultTableModel) tabelaMatriculados.getModel();
        this.tabelaDesjejum = (DefaultTableModel) this.desjejumTable.getModel();
        this.tabelaMaisEducacao1 = (DefaultTableModel) this.maisEducacaoTurno1.getModel();
        this.tabelaMaisEducacao2 = (DefaultTableModel) this.maisEducacaoTurno2.getModel();
        this.tabelaTotal = (DefaultTableModel) this.totalTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMatriculados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        proxButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mes = new java.awt.TextField();
        ano = new java.awt.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        desjejumTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        maisEducacaoTurno2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        maisEducacaoTurno1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        totalTable = new javax.swing.JTable();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setLabelFor(mes);
        jLabel1.setText("Mes ex: 3");

        tabelaMatriculados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PRÉ ESCOLAR", null, null, null, null, null, null, null, null},
                {"FUNDAMENTAL", null, null, null, null, null, null, null, null},
                {"JOVENS E ADULT", null, null, null, null, null, null, null, null},
                {"ENSINO ESP", null, null, null, null, null, null, null, null},
                {"Total", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Modalidade", "1º turno", "2º turno", "3º turno", "4º turno", "Total Matriculados", "Total atendidosl", "Nº dias de distribuição de refeição", "Total de refeições servidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaMatriculados);

        jLabel2.setLabelFor(tabelaMatriculados);
        jLabel2.setText("Alunos Matriculador");

        proxButton.setText("Próximo");
        proxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximaPagina(evt);
            }
        });

        jLabel3.setLabelFor(ano);
        jLabel3.setText("Ano ex: 2018");

        mes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });

        ano.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoActionPerformed(evt);
            }
        });

        desjejumTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Alunos Atendidos", "Total mensal servido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(desjejumTable);
        if (desjejumTable.getColumnModel().getColumnCount() > 0) {
            desjejumTable.getColumnModel().getColumn(0).setHeaderValue("Alunos Atendidos");
        }

        jLabel4.setText("Desjejum");

        maisEducacaoTurno2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Mais Educação", null, null, null, null, null, null}
            },
            new String [] {
                "Matriculados", "2º turno Matriculado", "2° turno Atendido", "Dias Distribuicao", "Total Desj. Servido", "Total lanche Servido", "Total Mais Educ."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(maisEducacaoTurno2);

        maisEducacaoTurno1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Mais Educação", null, null, null, null, null}
            },
            new String [] {
                "Matriculados", "1º turno Matriculado", "1° turno Atendido", "Dias Distribuicao", "Total Desj. Servido", "Total lanche Servido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(maisEducacaoTurno1);

        totalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Total mensal servido - Desjejum + Mais Ed."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(totalTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel2)))
                        .addGap(0, 367, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proxButton)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(proxButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**Método para atualizar a variavel capa com os valores contidos na tabelaMatricula
     * @author Joyce Brum
     */
    private void atualizaVetorMatriculados() {
        int [] turnos = new int[4];
        int atendidos;
        int numDias;
        for(int i = 0; i < this.tabelaMatricula.getRowCount(); i++) {
            for(int j = 1; j < 5; j++) {
                if(this.tabelaMatricula.getValueAt(i, j) != null) {
                    String valor = this.tabelaMatricula.getValueAt(i, j). toString(); 
                    turnos[j-1] = Integer.parseInt(valor);
                }
                else {
                    turnos[j-1] = 0;
                }
                
            }
            if(this.tabelaMatricula.getValueAt(i, 6) != null) {
                String valor = this.tabelaMatricula.getValueAt(i, 6).toString();
                atendidos = Integer.parseInt(valor);
            }
            else {
                atendidos = 0;
            }
            if(this.tabelaMatricula.getValueAt(i, 7) != null) {
                String valor = this.tabelaMatricula.getValueAt(i, 7).toString();
                numDias = Integer.parseInt(valor);
            }
            else {
                numDias = 0;
            }
            this.capa.setVetorMatriculados(i, turnos, atendidos, numDias);
        }
    }
    /**Método para atualizar a variavel capa com os valores contidos na tabela Desjejum
     * @author Joyce Brum
     */
    private void atualizaDesjejum() {
        int alunosAtendidos  = 0;
        int totalServido = 0;
        if(this.tabelaDesjejum.getValueAt(0, 0) != null) {
            alunosAtendidos = ((Integer)this.tabelaDesjejum.getValueAt(0, 0)).intValue();
        }
        if(this.tabelaDesjejum.getValueAt(0, 1) != null) {
            totalServido = ((Integer)this.tabelaDesjejum.getValueAt(0, 1)).intValue();
        }
        this.capa.setDesjejum(alunosAtendidos, totalServido);
    }
    /**Método para atualizar a variavel capa com os valores contidos na tabela 
     * Mais Educacao dos turnos 1 e 2
     * @author Joyce Brum
     */
    private void atualizaMaisEducacao1() {
        int [] valores = new int[5];
        for(int i = 1; i< this.tabelaMaisEducacao1.getColumnCount(); i++) {
            if(i > 5) {
                System.out.println("Erro ao atualizar capa sobre Mais Educação"); 
                continue;
            }
            if(this.tabelaMaisEducacao1.getValueAt(0, i) != null) {
                valores[i-1] = ((Integer)this.tabelaMaisEducacao1.getValueAt(0, i)).intValue();
            }
            else {
                valores[i-1] = 0;
            }
        }
        this.capa.setVetorMaisEducacao(0, valores[0], valores[1], valores[2], valores[3], valores[4]);
    }
    private void atualizaMaisEducacao2() {
        int [] valores = new int[5];
        for(int i = 1; i< this.tabelaMaisEducacao2.getColumnCount(); i++) {
            if(i > 5) {
                System.out.println("Erro ao atualizar capa sobre Mais Educação"); 
                continue;
            }
            if(this.tabelaMaisEducacao2.getValueAt(0, i) != null) {
                valores[i-1] = ((Integer)this.tabelaMaisEducacao2.getValueAt(0, i)).intValue();
            }
            else {
                valores[i-1] = 0;
            }
        }
        this.capa.setVetorMaisEducacao(1, valores[0], valores[1], valores[2], valores[3], valores[4]);
    }
    private void atualizaTotal() {
        this.tabelaTotal.setValueAt(this.capa.getTotalServido(), 0, 0);
    }
    private void atualizaCapaDados() {
        atualizaVetorMatriculados();
        atualizaDesjejum();
        atualizaMaisEducacao1();
        atualizaMaisEducacao2();
        atualizaTotal();
    }
    private void proximaPagina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximaPagina
        //String var = "aa13b";
        //var = var.replace("[a-zA-Z]", "");
        //System.out.println(var);
        if(this.mes.getText().intern() == null || this.mes.getText().intern() == "") {
            JOptionPane.showMessageDialog(null,"Campo mes obrigatório");
            return;
        }
        
        if(this.ano.getText().intern() == null || this.ano.getText().intern() == "") {
            JOptionPane.showMessageDialog(null,"Campo ano obrigatório");
            return;
        }
        
        int ano = Integer.parseInt(this.ano.getText());
        int mes = Integer.parseInt(this.mes.getText());
        this.capa = new CapaDados();
        atualizaCapaDados();
        cardapio=new TelaCardapio(ano, mes-1, this.capa);
        cardapio.setLocationRelativeTo(null);
        cardapio.setVisible(true);
        cardapio.setResizable(true);
        this.dispose();
    }//GEN-LAST:event_proximaPagina

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesActionPerformed

    private void anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField ano;
    private javax.swing.JTable desjejumTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable maisEducacaoTurno1;
    private javax.swing.JTable maisEducacaoTurno2;
    private java.awt.TextField mes;
    private javax.swing.JButton proxButton;
    private javax.swing.JTable tabelaMatriculados;
    private javax.swing.JTable totalTable;
    // End of variables declaration//GEN-END:variables
}
