/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package merendaprojectdb;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author thiago
 */
public class TelaSemanasRelatorio extends javax.swing.JFrame {

    TelaPrincipal principal;
    private Relatorio relatorio;
    private CapaDados capa;
    private Cardapio cardapio;
    private ArrayList<ItemComida> semana1List;
    private ArrayList<ItemComida> semana2List;
    private ArrayList<ItemComida> semana3List;
    private ArrayList<ItemComida> semana4List;
    private ArrayList<ItemComida> semana5List;
    private boolean editando;
    private String nomeRel;
    /**
     * Creates new form ItensRelatorio
     */
    public TelaSemanasRelatorio(String nomeRel, CapaDados capa, Cardapio cardapio) {        
        
        initComponents();
        this.capa = capa;
        this.cardapio = cardapio;
        this.editando = false;
        this.nomeRel = nomeRel;
        this.semana1List = new ArrayList<ItemComida>();
        this.semana2List = new ArrayList<ItemComida>();
        this.semana3List = new ArrayList<ItemComida>();
        this.semana4List = new ArrayList<ItemComida>();
        this.semana5List = new ArrayList<ItemComida>();
        
        // com essa parte podemos adicionar o dropBox com as coisas vindas do banco
    }
    public TelaSemanasRelatorio(Relatorio relatorio) {
        this.relatorio = relatorio;
        initComponents();
        this.semana1List = relatorio.semana1;
        this.semana2List = relatorio.semana2;
        this.semana3List = relatorio.semana3;
        this.semana4List = relatorio.semana4;
        this.semana5List = relatorio.semana5;
        this.editando = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        semana1 = new javax.swing.JButton();
        semana2 = new javax.swing.JButton();
        semana3 = new javax.swing.JButton();
        semana4 = new javax.swing.JButton();
        semana5 = new javax.swing.JButton();
        proximo = new javax.swing.JButton();
        voltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        semana1.setText("Semana 1");
        semana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semana1ActionPerformed(evt);
            }
        });

        semana2.setText("Semana 2");
        semana2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semana2ActionPerformed(evt);
            }
        });

        semana3.setText("Semana 3");
        semana3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semana3ActionPerformed(evt);
            }
        });

        semana4.setText("Semana 4");
        semana4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semana4ActionPerformed(evt);
            }
        });

        semana5.setText("Semana 5");
        semana5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semana5ActionPerformed(evt);
            }
        });

        proximo.setText("Finalizar");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        voltar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        voltar.setText("cancelar");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(semana4)
                    .addComponent(semana1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(semana2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(semana3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(proximo)))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(semana5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(voltar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltar)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semana1)
                    .addComponent(semana2)
                    .addComponent(semana3))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semana4)
                    .addComponent(semana5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(proximo)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void semana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semana1ActionPerformed
        TelaItensRelatorio itensRel = new TelaItensRelatorio(this.semana1List, this);
        itensRel.setLocationRelativeTo(null);
        itensRel.setVisible(true);
        itensRel.setResizable(true);
        this.setVisible(false);
    }//GEN-LAST:event_semana1ActionPerformed
    private void atualizaListas() {
        this.relatorio.semana1 = this.semana1List;
        this.relatorio.semana2 = this.semana2List;
        this.relatorio.semana3 = this.semana3List;
        this.relatorio.semana4 = this.semana4List;
        this.relatorio.semana5 = this.semana5List;
    }
    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        if(!this.editando) {
            this.relatorio = new Relatorio (this.cardapio.getMes(), this.cardapio.getAno(),this.nomeRel, 
                                            TelaPrincipal.escolaAtual, this.cardapio, this.capa);
            atualizaListas();
            if(BdManager.adicionarRelatorio(this.relatorio)) {
                TelaPrincipal.usuarioLogado.idRelatorio = new IdentificacaoRelatorio(this.relatorio.getEscola().getINEP(),
                this.relatorio.getMes(), this.relatorio.getAno());
            }
            else {
                JOptionPane.showMessageDialog(null,"Houve um erro ao salvar o relatório no banco");
            }
        }
        else
        {
            //atualizaListas();
            BdManager.alterarRelatorio(this.relatorio);
        }
        principal=new TelaPrincipal();
        principal.setLocationRelativeTo(null);
        principal.setVisible(true);
        principal.setResizable(true);
        this.dispose();
    }//GEN-LAST:event_proximoActionPerformed

    private void semana2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semana2ActionPerformed
        TelaItensRelatorio itensRel = new TelaItensRelatorio(this.semana2List, this);
        itensRel.setLocationRelativeTo(null);
        itensRel.setVisible(true);
        itensRel.setResizable(true);
        this.setVisible(false);
    }//GEN-LAST:event_semana2ActionPerformed

    private void semana3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semana3ActionPerformed
        TelaItensRelatorio itensRel = new TelaItensRelatorio(this.semana3List, this);
        itensRel.setLocationRelativeTo(null);
        itensRel.setVisible(true);
        itensRel.setResizable(true);
        this.setVisible(false);
    }//GEN-LAST:event_semana3ActionPerformed

    private void semana4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semana4ActionPerformed
        TelaItensRelatorio itensRel = new TelaItensRelatorio(this.semana4List, this);
        itensRel.setLocationRelativeTo(null);
        itensRel.setVisible(true);
        itensRel.setResizable(true);
        this.setVisible(false);    }//GEN-LAST:event_semana4ActionPerformed

    private void semana5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semana5ActionPerformed
        TelaItensRelatorio itensRel = new TelaItensRelatorio(this.semana5List, this);
        itensRel.setLocationRelativeTo(null);
        itensRel.setVisible(true);
        itensRel.setResizable(true);
        this.setVisible(false);
    }//GEN-LAST:event_semana5ActionPerformed

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        int i = JOptionPane.showConfirmDialog(null ,"Tem certeza que deseja sair?", "Saída",JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            principal=new TelaPrincipal();
            principal.setLocationRelativeTo(null);
            principal.setVisible(true);
            principal.setResizable(true);
        this.dispose();
        }        
    }//GEN-LAST:event_voltarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton proximo;
    private javax.swing.JButton semana1;
    private javax.swing.JButton semana2;
    private javax.swing.JButton semana3;
    private javax.swing.JButton semana4;
    private javax.swing.JButton semana5;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables
}
