-- MySQL Script generated by MySQL Workbench
-- sáb 07 jul 2018 23:14:04 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema merenda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `merenda` ;

-- -----------------------------------------------------
-- Schema merenda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `merenda` DEFAULT CHARACTER SET utf8 ;
USE `merenda` ;

-- -----------------------------------------------------
-- Table `merenda`.`alimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`alimento` ;

CREATE TABLE IF NOT EXISTS `merenda`.`alimento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `perecivel` TINYINT(4) NULL DEFAULT NULL,
  `qtd_atende` INT(11) NULL DEFAULT NULL,
  `medida` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `fornecedor` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `marca` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`tipo_instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`tipo_instituicao` ;

CREATE TABLE IF NOT EXISTS `merenda`.`tipo_instituicao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`instituicao` ;

CREATE TABLE IF NOT EXISTS `merenda`.`instituicao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_tipo` INT(11) NOT NULL,
  `nome` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `inep` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `endereco` VARCHAR(120) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `qtd_alunos` INT(11) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_tipo`),
  INDEX `fk_instituicao_tipo_idx` (`id_tipo` ASC),
  CONSTRAINT `fk_instituicao_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `merenda`.`tipo_instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`cardapio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`cardapio` ;

CREATE TABLE IF NOT EXISTS `merenda`.`cardapio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_instituicao` INT(11) NOT NULL,
  `data_cardapio` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `lanche_manha` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `almoco` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `lanche_tarde` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `janta` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cardapio_instituicao_idx` (`id_instituicao` ASC),
  CONSTRAINT `fk_cardapio_instituicao`
    FOREIGN KEY (`id_instituicao`)
    REFERENCES `merenda`.`instituicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `merenda`.`pessoa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `cpf` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`tipo_conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`tipo_conta` ;

CREATE TABLE IF NOT EXISTS `merenda`.`tipo_conta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`conta` ;

CREATE TABLE IF NOT EXISTS `merenda`.`conta` (
  `id_pessoa` INT(11) NOT NULL,
  `id_instituicao` INT(11) NOT NULL,
  `id_tipo_conta` INT(11) NULL DEFAULT NULL,
  `matricula` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `usuario` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `senha` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_pessoa`, `id_instituicao`),
  INDEX `fk_conta_instituicao_idx` (`id_instituicao` ASC),
  INDEX `fk_conta_tipo_idx` (`id_tipo_conta` ASC),
  CONSTRAINT `fk_conta_instituicao`
    FOREIGN KEY (`id_instituicao`)
    REFERENCES `merenda`.`instituicao` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `merenda`.`pessoa` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_tipo`
    FOREIGN KEY (`id_tipo_conta`)
    REFERENCES `merenda`.`tipo_conta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`nota_fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`nota_fiscal` ;

CREATE TABLE IF NOT EXISTS `merenda`.`nota_fiscal` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data_emissao` VARCHAR(10) NULL DEFAULT NULL,
  `imagem` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`entrega` ;

CREATE TABLE IF NOT EXISTS `merenda`.`entrega` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_nota_fiscal` INT(11) NOT NULL,
  `id_instituicao` INT(11) NOT NULL,
  `data_entrega` VARCHAR(10) NULL DEFAULT NULL,
  `fornecedor` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `id_nota_fiscal`),
  INDEX `fk_entrega_nota_fiscal1_idx` (`id_nota_fiscal` ASC),
  INDEX `fk_entrega_instituicao1_idx` (`id_instituicao` ASC),
  CONSTRAINT `fk_entrega_instituicao1`
    FOREIGN KEY (`id_instituicao`)
    REFERENCES `merenda`.`instituicao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_nota_fiscal1`
    FOREIGN KEY (`id_nota_fiscal`)
    REFERENCES `merenda`.`nota_fiscal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`lote` ;

CREATE TABLE IF NOT EXISTS `merenda`.`lote` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_alimento` INT(11) NOT NULL,
  `preco` FLOAT NULL DEFAULT NULL,
  `qtd_alimento` INT(11) NULL DEFAULT NULL,
  `data_validade` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lote_item1_idx` (`id_alimento` ASC),
  CONSTRAINT `fk_lote_item1`
    FOREIGN KEY (`id_alimento`)
    REFERENCES `merenda`.`alimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`encomenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`encomenda` ;

CREATE TABLE IF NOT EXISTS `merenda`.`encomenda` (
  `id_lote` INT(11) NOT NULL,
  `id_entrega` INT(11) NOT NULL,
  `id_nota_fiscal` INT(11) NOT NULL,
  PRIMARY KEY (`id_lote`, `id_entrega`, `id_nota_fiscal`),
  INDEX `fk_lote_has_entrega_entrega1_idx` (`id_entrega` ASC, `id_nota_fiscal` ASC),
  INDEX `fk_lote_has_entrega_lote1_idx` (`id_lote` ASC),
  CONSTRAINT `fk_lote_has_entrega_entrega1`
    FOREIGN KEY (`id_entrega` , `id_nota_fiscal`)
    REFERENCES `merenda`.`entrega` (`id` , `id_nota_fiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lote_has_entrega_lote1`
    FOREIGN KEY (`id_lote`)
    REFERENCES `merenda`.`lote` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`saida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`saida` ;

CREATE TABLE IF NOT EXISTS `merenda`.`saida` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `qtd_remanejo` INT(11) NULL DEFAULT NULL,
  `qtd_usado` INT(11) NULL DEFAULT NULL,
  `qtd_ata` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`estoque` ;

CREATE TABLE IF NOT EXISTS `merenda`.`estoque` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_entrada` INT(11) NOT NULL,
  `id_saida` INT(11) NOT NULL,
  `qtd_atual` INT(11) NULL DEFAULT NULL,
  `data_estoque` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estoque_entrada1_idx` (`id_entrada` ASC),
  INDEX `fk_estoque_saida1_idx` (`id_saida` ASC),
  CONSTRAINT `fk_estoque_entrada1`
    FOREIGN KEY (`id_entrada`)
    REFERENCES `merenda`.`entrada` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoque_saida1`
    FOREIGN KEY (`id_saida`)
    REFERENCES `merenda`.`saida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `merenda`.`entrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `merenda`.`entrada` ;

CREATE TABLE IF NOT EXISTS `merenda`.`entrada` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_entrega` INT(11) NOT NULL,
  `id_nota_fiscal` INT(11) NOT NULL,
  `id_estoque_anterior` INT(11) NOT NULL,
  `qtd_remanejo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entrada_entrega1_idx` (`id_entrega` ASC, `id_nota_fiscal` ASC),
  INDEX `fk_entrada_estoque1_idx` (`id_estoque_anterior` ASC),
  CONSTRAINT `fk_entrada_entrega1`
    FOREIGN KEY (`id_entrega` , `id_nota_fiscal`)
    REFERENCES `merenda`.`entrega` (`id` , `id_nota_fiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrada_estoque1`
    FOREIGN KEY (`id_estoque_anterior`)
    REFERENCES `merenda`.`estoque` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

--
-- Dumping data for table `tipo_instituicao`
--

LOCK TABLES `tipo_instituicao` WRITE;
/*!40000 ALTER TABLE `tipo_instituicao` DISABLE KEYS */;
INSERT INTO `tipo_instituicao` VALUES (0,'Secretaria de Educação'),(0,'Escola Tipo A'),(0,'Escola Tipo B'),(0,'Escola Tipo C');
/*!40000 ALTER TABLE `tipo_instituicao` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `instituicao`
--

LOCK TABLES `instituicao` WRITE;
/*!40000 ALTER TABLE `instituicao` DISABLE KEYS */;
INSERT INTO `instituicao` VALUES (0,1,'sdaffads','12345678','Rua da Gazela',50,'2140028922'),(0,4,'Colegin do titio','12345678','Rua da Jaca 186 223',600,'2140028923');
/*!40000 ALTER TABLE `instituicao` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `pessoa`
--

LOCK TABLES `pessoa` WRITE;
/*!40000 ALTER TABLE `pessoa` DISABLE KEYS */;
INSERT INTO `pessoa` VALUES (0,'Andre','10010010010'),(0,'Bruna','20020020020');
/*!40000 ALTER TABLE `pessoa` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `tipo_conta`
--

LOCK TABLES `tipo_conta` WRITE;
/*!40000 ALTER TABLE `tipo_conta` DISABLE KEYS */;
INSERT INTO `tipo_conta` VALUES (0,'Administrador'),(0,'Diretor'),(0,'Leitor');
/*!40000 ALTER TABLE `tipo_conta` ENABLE KEYS */;
UNLOCK TABLES;


--
-- Dumping data for table `conta`
--

LOCK TABLES `conta` WRITE;
/*!40000 ALTER TABLE `conta` DISABLE KEYS */;
INSERT INTO `conta` VALUES (1,1,1,'1001001001','root','root');
/*!40000 ALTER TABLE `conta` ENABLE KEYS */;
UNLOCK TABLES;
